###
# swagger-editor - https://github.com/swagger-api/swagger-editor/
#
# Run the swagger-editor service on port 8080
###

FROM    vsheffer/grunt
MAINTAINER Marcello_deSales@intuit.com

ADD     bower.json      /runtime/bower.json
ADD     .bowerrc        /runtime/.bowerrc
RUN     bower --allow-root install

ADD     .   /runtime
RUN 	grunt build

RUN     cp /runtime/.tmp/styles/main.css /runtime/app/styles/

# The default port of the application
EXPOSE  8080
#CMD     grunt serve
CMD [ "/usr/bin/gitrest", "-repo-dir=/var/local/data/swagger-specs", "-static-dir=/runtime/app/" ]
