###
# swagger-editor - https://github.com/swagger-api/swagger-editor/
#
# Run the swagger-editor service on port 8080
###

FROM    bhnetwork/grunt
MAINTAINER Marcello_deSales@intuit.com

ADD     bower.json      /runtime/bower.json
ADD     .bowerrc        /runtime/.bowerrc
RUN     bower --allow-root install

ADD     .   /runtime
RUN 	grunt build

# The default port of the application
EXPOSE  8080
CMD [ "/usr/bin/gitrest", "-repo-dir=/var/local/data/swagger-specs", "-static-dir=/runtime/dist/" ]
